version: 'build #{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  PATH: C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%

install:
  - pacman -Syuu --ask 20 --noconfirm
  - pacman -Syuu --ask 20 --noconfirm
  - pacman -Syuu --ask 20 --noconfirm
  - pacman -S mingw-w64-x86_64-clang --noconfirm
  - clang --version -v

build_script:
  - mkdir build
  - clang -O3 -c src/main/c/pi.c -o build/pi.o && ar rc build/pi.a build/*.o
  - clang -O3 src/main/c/main.c build/pi.a -lm -o build/pi-c.exe
  - gradlew --no-daemon --info build
  - pushd build && 7z a Pi-windows.zip pi-c.exe .\konan\bin\mingw\pi-interop.exe .\konan\bin\mingw\pi-konan.exe && popd
  - ls -l build

test_script:
  - ps: 1..5 | % {(Measure-Command {build/pi-c 1000}).TotalSeconds} | Measure-Object -Average
  - ps: 1..5 | % {(Measure-Command {build/konan/bin/mingw/pi-interop 1000}).TotalSeconds} | Measure-Object -Average
  - ps: 1..5 | % {(Measure-Command {build/konan/bin/mingw/pi-konan 1000}).TotalSeconds} | Measure-Object -Average

artifacts:
  - path: build\Pi-windows.zip
    name: build

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  artifact: build
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
