language: java
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

script:
  - mkdir build
  - clang --version -v
  - clang -O3 -c src/main/c/pi.c -o build/pi.o && ar rc build/pi.a build/*.o
  - clang -O3 src/main/c/main.c build/pi.a -lm -o build/pi-c
  - ./gradlew --no-daemon --info build
  - cp build/konan/bin/*/pi-konan.kexe build/pi-konan
  - cp build/konan/bin/*/pi-interop.kexe build/pi-interop
  - cd build && tar -czf "Pi-${TRAVIS_OS_NAME}.tgz" pi-c pi-konan pi-interop && cd ..

deploy:
  provider: releases
  api_key:
    secure: aBqMGilTH04aeNSnjr8x++KF/wrCMeuI/whHAdWnnmV7aJLF7qPH+doGMfpw8grqEtpmp/kyoFEbGiFsucxIuvnGjNpNZV3XMWh8bsuz+5y3JCix0gzvPr4yb8CQmcmCs7Mz1FtfrfPSaubsZ3lJRvK1GQ+d+ZGco2rR2SXtnaKznA1ERzEheTgFNHX0H9EidSzlQUVaQyksFAB4pj1/7726Tg9T5pF/81bECG4xJOkGM+k6pA10UVGXhtMsNo8FpUzL1LqDNWlOAfLL3ajvT6XEfWwnsQ+lX8gx26+OVhdhLf177OWuuVy0Cc0/Y/Tywv951nHnfBbEZxs73U53AZEaxf1Z/1WFO6pio+EdJUUWfUCNH7U83T3a1uSueF2dcs5TSbNXLWt3x9AEGMwy5P21MdrXGpWpD3KJ+AA+Wqdl/emW8E6Rl/Qa/eYOK8CDogZk1KaGn+0WE2tGj9fgVKEJ7c27eHTmrWhDp99iwy+c14MMkVIgoNOeDA2xMWv3u9g0P2DJj4OCcoQkJQcsncTA5gsgDE4D1b6rS/DjYF44Rze+S8HGdahxeqNdSxcVa5XglJUuN8G4C7HdbSlAqrih7jPvKAFwIRJxLMnVUZdtpUaDHycjM3wEWbUY6uLesSXwabSSk0I/BtwTInfIwDy1LYKy3Rz1M1lnA7UiVkU=
  file: build/*.tgz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: msink/kotlin-pi
