language: java
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

script:
  - mkdir build
  - clang --version -v
  - clang -O3 -c src/main/c/pi.c -o build/pi.o && ar rc build/pi.a build/*.o
  - clang -O3 src/main/c/main.c build/pi.a -lm -o build/pi-c
  - ./gradlew --no-daemon --info build
